### ISSUE TITLE
[BUG] Hover state sticks after key is pressed

### ISSUE THREAD

**Issue by dukuo** [TeamRocketThesis/react-vr-textinput#61]
# DESCRIPTION
After fresh install of the package and `yarn start` pressing the keys will ocassionally cause the hover state of the pressed key to stick, only going back normal state if the key is hovered again. 

## ACTUAL BEHAVIOUR
Hover state of keys ocassionally sticks 

## EXPECTED BEHAVIOUR
onExit'ing key should turn it back to normal state. 

## BROWSER, DEVICES AND PLATFORMS
**Desktop:** Google Chrome 58.0.3029.110 (64-bit) / Windows 10 Creators Update
**Mobile:** Google Chrome 58.0.3029.83 / Samsung S6 Edge SM-G925V / Android 6.0.1/

**Comment by Simmba** [comment]
I tried to address this in the latest revision. Could you please test it out again? With the new changes I am not able to reproduce this error.

**Comment by ArseniyKotov** [comment]
Closed because unable to reproduce
