### ISSUE TITLE
There seems to be a typo in index.js

### ISSUE THREAD

**Issue by chira-pym** [TeamRocketThesis/react-vr-textinput#67]
On the react-vr-textinput/index.js file:

```javascript
module.exports = require('./src/TextInput');
```

'./src/TextInput' should  probably be './src/textInput' ?

**Comment by ArseniyKotov** [comment]
For some reason the file name keeps changing in between git commits. I'm going to fix this now and issue a new release.

Let me know if this fixes the issue.

**Comment by chira-pym** [comment]
I can confirm the issue is fixed.

Thank you.
