### ISSUE TITLE
Demo in the description/readme

### ISSUE THREAD

**Issue by nikgraf** [TeamRocketThesis/react-vr-textinput#68]
I found your repo. It would be really cool if you could provide a demo (can be hosted on Github pages)

btw also added this component to the awesome-react-vr list https://github.com/nikgraf/awesome-react-vr#frameworks-and-components

**Comment by Simmba** [comment]
Hi nikgraf,
I'll try to get a demo out soon. Life has been super busy and this project was put aside for a period of time. Thank you so much for the suggestion! We, the team, appreciate it! :D

**Comment by horacioh** [comment]
i want to try some things with React360 and the only textInput I found is this one but id does not work with the current `react-360` generated code.

is this project dead? do you need help with something? 

thanks!

**Comment by horacioh** [comment]
I found this project and is working quite well: https://github.com/danielbuechele/react-360-keyboard

maybe @nikgraf you can update this in your `awesome-react-vr` repo?

**Comment by nikgraf** [comment]
@horacioh happy to accept a PR to the awesome-react-360 repo

**Comment by horacioh** [comment]
[Done!](https://github.com/nikgraf/awesome-react-360/pull/13)
